ManageIQ/manageiq.org

- source/download/index.html.haml
> Added changelog to download page

- .travis.yml
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
> Change to use Dockerized Travis and bundle caching

- source/download/index.html.haml
- source/stylesheets/lib/site.sass
> support release candidates & editable values

- source/blog/2015-06-05-ui-login-button-fails-after-git-pull.html.md
Please review @Fryguy @dclarizio @brandondunne @chessbyte @seandst 
This started as a quick blog post but I tried to pull in Jason's suggestion from the [talk discussion](http://talk.manageiq.org/t/update-manage-iq/719).
> Add blog post about unresponsive UI elements after running git pull.

- data/team.yml
Add Dan Berger’s bio information.
[skip ci]
> Add Dan Berger

- data/team.yml
Laura Galis
add freenode for greggt
> Update for Laura Galis

- source/community/install-from-source.html.md
https://github.com/ManageIQ/manageiq/pull/3295
> Fixed broken link on 'Install from source' page

- source/community/install-from-source.html.md
Those steps are missing from docs.
> Add rake db:migrate, rake db:seed and bin/rake evm:start to docs

- source/blog/2015-09-24-announcing-the-alpha-release-of-capablanca.html.md
This is the Alpha release of Capablanca blog.
> Added 092415 blog

- source/blog/2015-10-13-announcing-the-beta-release-of-capablanca.md
If the beta is indeed ready to go, this announcement is ready to go.
> Added 2015-10-13 beta announcement

- source/blog/2015-09-24-announcing-the-alpha-release-of-capablanca.html.md
Spoke to @abellotti.  Appliance does not include FreeIPA, but has been tested against it.
> Edit FreeIPA statement

- source/blog/2015-10-13-announcing-the-beta-release-of-capablanca.md
The previous link went to the PR, not the file.
> Fix link to changelog

- data/team.yml
Added my general information to the team list
> Updated team.yml with my bio.

- data/releases.yml
- source/download/index.html.haml
@matthewd @chessbyte Please review.
> Release capablanca-1-rc2

- data/authors.yml
- source/blog/2015-11-19-announcing-capablanca-rc2.html.md
> Announce Capablanca RC2

- data/navigation.yml
- source/blog.html.haml
- source/index.html.haml
- source/stylesheets/_bootstrap-custom.sass
- source/stylesheets/lib/site.sass
> Move news to navigation

- data/team.yml
> Chris Arcand bio

- source/community/community-guidelines.html.md
linked to talk category instead
> removed broken talk.manageiq.org link in the community section.

- source/download/index.html.haml
> Reference to devel images in glance command

- config.rb
- data/deploy_releases.yml
- data/deploy_types.yml
- data/releases.yml
- source/download/index.html.haml
- source/index.html.haml
- source/stylesheets/lib/site.sass
@chessbyte @geertj @matthewd I wanted to see what it would look like (and how hard it would be) to create a simpler download page.  I can't seem to push to a webserver because all of the generated URLs are absolute, so a screencast will have to do.  This PR does not have the build_url or build_filenames working yet, but it does give a feel for how the page shows and hides stuff
What do you think?  The styling is terrible and I can't figure out how to do anything nice, so I'm starting to get into  very unfamiliar territory.
> New download page

- data/deploy_types.yml
- source/download/index.html.haml
- source/index.html.haml
@geertj @chessbyte Please review.  The download link should say "vsphere" not "vmware"
> Fix download links for vSphere

- data/authors.yml
- source/blog/2016-02-26-announcing-manageiq-design-summit-june-6-7-2016-save-the-date.html.md
Adding the Design Summit announcement post and my author info to the ManageIQ blog
> Add blog post to announce ManageIQ Design Summit 2016

- source/blog/2016-03-03-manageiq-design-summit-2016-call-for-papers.html.md
Adding a blog post to announce the opening of CFP for the Design Summit.
> Blog post for Design Summit CFP

- data/team.yml
> added Yuri Rudman to team.yml

- source/documentation/index.html.haml
> Fix REST API documentation link

- data/deploy_types.yml
- source/download/index.html.haml
WIP until I can get instructions with @JPrause 
I also have to temporarily block stable downloads until darga because we don't have one for capablanca.  If we can create a capablanca-2 vhd, then I can remove that bit in this PR.
> Add VHD to download page.

- source/blog/2016-03-31-sprint-38-review-march-30-2016.html.md
Overview of Sprint 38 review with links to the meeting video and slides. 
@chessbyte @Fryguy please check for accuracy, thanks!
> Sprint 38 review blog post

- data/deploy_releases.yml
@chessbyte Please review.  This should only be merged after darga-1-beta1 is built and available on releases.manageiq.org.
> Expose darga-1-beta1 prelease on download page

- .gitmodules
- config.rb
Removing extensions viewer and git submodule
> More config changes for removal of previous community depot

- source/summit/index.html.haml
Updates to speakers/title for Openstack and oVirt talks
> Couple of minor changes to summit agenda

- source/community/index.html.haml
@blomquisg @Fryguy @chessbyte please review. thanks
> Remove duplicate link to developer setup page

- source/summit/index.html.haml
The presentation on Monday at 15:30 titled "Self-Service UI (Dan Clarizio, Greg McCullough)" has different presenters of "Self-Service UI (Hapreet Kataria, Erik Clarizio)".
> Update speakers for Self-service UI talk

- source/summit/index.html.haml
Add co-presenters to OpenStack talk; BAH unconfirmed, removing for now.
> More summit speakers and sponsor updates

- source/summit/index.html.haml
Drop GregM from "ManageIQ and Ansible" talk
> One more (last?) modification to summit agenda

- source/summit/index.html.haml
Switching Cloud Networking and Pluggable Providers slots, and adding location details to the schedule.
> Add room location details; swap speaking slots

- data/deploy_releases.yml
- source/download/index.html.haml
> Release darga-1

- source/documentation/index.html.haml
This depends on pdf files being uploaded to the server.
And of course it depends on Darga being released.
This is what the rendered page now looks like:
> Update PDF links for Darga release.

- source/blog/2016-06-20-presentation-slides-and-demo-videos-from-manageiq-design-summit.html.md
Blog post for sharing the uploaded presentations slides and demo videos (not session recordings) in a more organized and accessible way.
> Presentation slides and demo videos blog post

- data/deploy_releases.yml
> Release darga-2

- source/blog/2016-06-30-darga-2-announcementt.html.md
Edit as much as you want. Short, sweet...
[skip ci]
> Darga rc-2 blog post

- source/blog/2016-06-30-darga-2-announcementt.html.md
> Update blog to have correct date

- data/authors.yml
Incorrect description of mfeifer
> Remove author description for mfeifer

- source/blog/2016-07-26-last-week-in-manageiq-faster-reports-cloud-networks-and-more.md
Thanks @cybette for tracking this down! :heart:
> Put title in quotes to escape :

- source/blog/2016-07-26-last-week-in-manageiq-faster-reports-cloud-networks-and-more.md
It's already built into the page from the configuration/layout, so this
looks super silly
> Remove header for LWIMIQ post

- source/layouts/_blog_posts.haml
The line is currently getting it's color from Bootstrap and is a little faint. Will change in future.
> Break up blog posts with line

- source/blog/2016-07-29-sprint-43-review-july-13-2016.html.md
Summary of Sprint 43 review with links to the meeting videos and slides. Also added a plug for "Last Week in ManageIQ" blog series.
> Sprint 43 review blog post

- data/authors.yml
- source/blog/2016-08-09-last-week-in-manageiq.md
> Last week in MIQ 2016-08-09

- source/blog/2016-08-22-Announcing-Darga-3.html.md
Filter was missing PRs that were merged for darga-3
> Fixed urls for merged date and not created date

- source/index.html.haml
@cybette Can you check if you are OK with this change? :blush:
> Removed teaser for the Summit from main page

- source/blog/2016-08-22-last-week-in-manageiq-the-azure-nice-errors-and-gems.html.md
Extra space around Bronagh's name stopped the link being rendered.
> Removed extra space in markup

- data/team.yml
> Updates to add missing team members and remove others

- source/blog/2016-08-19-sprint-44-review-august-3-2016.html.md
- source/blog/2016-09-09-sprint-45-review-august-24-2016.html.md
- source/blog/2016-09-16-sprint-46-review-september-14-2016.html.md
While I was working on Sprint 46 blog post yesterday I noticed I left the previous two WIP (probably waiting for changelog). I need to track my own work better :sweat_smile: 
Cleaned up the posts, added changelog, fixed Bluejeans link, submit PR.
> Sprint review 44 - 46 blog posts

- data/team.yml
Adding new team member as well as updates to existing profiles.
> Updates for ManageIQ team page

- source/blog/2016-09-16-sprint-46-review-september-14-2016.html.md
Blog post was written before changelog was finalised and merged, so adding it now that changelog is available.
> Add changelog to Sprint 46 review post

- data/authors.yml
- source/blog/2016-09-26-last-week-in-manage-iq-builders-basecontrollers-bugs-backend-booting.html.md
The 'B' blogpost to follow up Drew's 'A' post. Although, not quite as flashy, I admit.
> Sept 26th blogpost

- data/deploy_releases.yml
- source/blog/2016-10-06-Announcing-Darga-4.html.md
Current release date Oct 04, 2016
> Announcing Darga-4

- .travis.yml
- lib/miq/ref_docs.rb
Ruby version needs to be >= 2.2.2
> Fix Travis config

- site/docs/get-started/concepts.md
Using previous work on my side and including changes proposed by
#351 
All appliance names have been changed to ManageIQ
> update in concepts

- site/_includes/analytics.html
- site/_layouts/default.html
Adding google analytics code to the site. @hayesr do you use the jekyll production/development env when building, or is there something else I should use?
> Add Google Analytics

- site/_assets/css/_features.scss
- site/_assets/css/_platforms.scss
- site/_assets/css/_solutions.scss
- site/_assets/css/_triad.scss
- site/_assets/css/_type.scss
Improves the solutions and features sections for desktop and mobile.
----
> Homepage style improvements

- site/_includes/triad.html
Changes "take 10 minutes to get started …" to 30 minutes.
> More realistic getting started time.

- site/_includes/solutions.html
Fixes a typo on the front page
> Fix “continous” typo

- source/blog/2016-10-06-Announcing-Darga-4.1.html.md
Was pointing at master branch.
> Fixed url to point to darga changelog

- site/_posts/2016-10-10-lwimiq-hacktoberfest-faster-trees-chargeback-reports.md
@hayesr LMK if I need to do anything special for this to be deployed. Thanks!
> Add LWIMIQ 2016-10-10

- site/_assets/css/_type.scss
- site/_posts/2016-10-13-Announcing-Euwe-Beta-Release.html.md
* Fixes the rendering of the table in the blog post.
* Adds some basic CSS to style the table
> Fix blog table

- site/docs/get-started/vagrant.md
Changed the description of the vagrant box to the official vagrant box
> Adding new vagrant box

- site/_posts/2016-10-17-last-week-in-manageiq-conversations-lead-to-merges.html.md
Last week in ManageIQ - 10-17-2016
> Conversations lead to merges blog post

- Dockerfile
Adds a volume to the Dockerfile for Let's Encrypt.
> Changes to Dockerfile

- lib/miq/lwimiq.rb
Oops. Apparently I checked that this was working, but not that it created the post in the right folder. This should fix it
@miq-bot assign @hayesr
> Fix lwimiq generator path

- site/_data/releases.yaml
> Update releases for euwe-RC

- site/_posts/2016-10-26-Announcing-Euwe-Release-Candidate.html.md
- site/_posts/2016-10-27-Announcing-Euwe-Release-Candidate.html.md
Initial submission. Will need updates for changelog and release downloads.
> Announcement for Euwe RC

- site/_data/download_types.yaml
- site/_data/releases.yaml
- site/download/index.md
Update download file sizes and Vagrant box info
> Changes to Download

- site/_posts/2016-10-28-sprint-48-review-october-26-2016.html.md
Recap of Sprint 48 review with links to the meeting video and slides.
> Sprint 48 review blog post

- site/_posts/2016-11-11-vote-on-naming-f-release.html.md
Need to update the url to the talk subject once created.
> F-Release voting information

- site/_posts/2016-11-14-last-week-in-manageiq-azure-provider-is-moved-to-gem.html.md
A new entry for Last Week in ManageIQ.
> LWIMIQ - Azure provider is moved to gem - Nov 7 to Nov 13

- site/_posts/2016-11-18-sprint-49-review-november-16-2016.html.md
Recap of Sprint 49 review with links to the meeting video and slides.
> Sprint 49 review blog post

- site/_data/releases.yaml
- site/_posts/2016-11-18-Announcing-Euwe-Release-Candidate-2.html.md
Still need to updates file sizes once appliance builds have completed.
> Announcement for Euwe RC2

- site/_posts/2016-11-21-announce_f_name.html.md
Need to update with final results.
> F-Release voting results

- site/_posts/2016-11-21-announce_f_name.html.md
> Fixing time for F announcement

- site/_assets/css/_footer.scss
- site/_assets/css/_header.scss
- site/_assets/css/_mixins.scss
- site/_assets/css/_off_canvas.scss
- site/_assets/css/_site_nav.scss
- site/_includes/header.html
- site/assets/js/_header.coffee
- site/assets/js/_site_menu.coffee
This increases the size of tap areas for the off-canvas menu on mobile, along with other visual improvements.
/cc @Fryguy
> Menu improvements

- site/_posts/2016-11-21-last-week-in-manageiq-euwe_stabilization_continues.html.md
/cc @imtayadeway, @JPrause - please review
> 2016-11-21 - Last week in ManageIQ – Euwe stabilization continues

- site/_posts/2016-11-28-fixing-bugs.md
@hayesr FYI we don't support this syntax :cry:
> Removed embedded image from my post as it was not rendered

- README.md
- site/_assets/css/_docs.scss
- site/_assets/css/_lightbox.scss
- site/_assets/css/_mixins.scss
- site/_assets/css/_page.scss
- site/_assets/css/main.scss
- site/_includes/lightbox.html
- site/_layouts/default.html
- site/_posts/2016-11-28-fixing-bugs.md
- site/assets/js/_lightbox.coffee
- site/assets/js/main.coffee
- site/docs/get-started/add-a-provider.md
- site/docs/get-started/basic-configuration.md
- site/docs/get-started/cloud.md
- site/docs/get-started/create-service-item.md
- site/docs/get-started/provision-machine.md
- site/docs/get-started/review-provider.md
This restricts large images to their container, and provides a way to embiggen them when clicked upon.
/cc @skateman
> Adds a lightbox implementation for large images

- site/_data/releases.yaml
- site/_posts/2016-12-05-Announcing-Darga-5.html.md
Announcement for Darga 5 release.
> [WIP] Announce-Darga5

- site/_posts/2016-12-09-sprint-50-review-december-7-2016.html.md
Recap of Sprint 50 review with links to the meeting video and slides.
> Sprint 50 review blog post

- site/_includes/triad.html
- site/docs/get-started/cloud.md
- site/docs/get-started/docker.md
- site/docs/get-started/vagrant.md
Updating the getting started guides for the Euwe release
@sergio-ocon please review, let me know if there are files I missed
@geertj are you doing the GCE builds? perhaps you can instruct me how to do it and I can take care of them going forward
@hayesr this should be merged when Euwe GA goes live
@cybette note to self: update GCE screenshots?
> Update docs from Darga to Euwe

- site/_data/releases.yaml
> Update for euwe ga

- site/download/index.md
Add check for pre-releases, omit download section if there are none.
> Update Download page for Euwe GA

- site/_data/download_types.yaml
- site/download/index.md
> More changes to Download for Euwe GA

- site/community.md
- Stats widget from openhub.net
- Links to members/contributors on github
> Add project stats and link to contributors

- site/_posts/2017-01-03-last-week-in-manageiq-a-brand-new-euwe.md
Covers the two weeks over the holidays.
> The one where we wrote last two weeks in manageIQ

- site/_posts/2017-01-06-sprint-51-review-january-4-2017.html.md
Recap of Sprint 51 review with links to the meeting video and slides.
> Sprint 51 review blog post

- Dockerfile
This points the dockerfile at Manageiq/manageiq_docs
> Change to use official manageiq_docs repo

- site/_posts/2017-01-11-year-in-review-2016.html.md
Summarizing ManageIQ activities and progress in 2016
> 2016 Year in review blog post

- site/_posts/2017-01-16-destroy-the-monolith.md
bring out the [Grammar Police](https://www.youtube.com/watch?v=NDbnkYSLwI0)
@JPrause please review
> lwimiq 2017-01-16

- site/_posts/2017-01-06-sprint-51-review-january-4-2017.html.md
- site/_posts/2017-01-20-sprint-52-review-january-18-2017.html.md
- Recap of Sprint 52 review with links to the meeting video and slides.
- Also add changelog to Sprint 51 blog post.
> Sprint 52 review blog post

- site/_posts/2017-01-23-last-week-in-manageiq-last-will-be-first.html.md
This is the Last Week in ManageIQ blog post for Jan 23.
> 2017-01-23 - Last Week in ManageIQ: The last will be the first

- site/_data/menus/api_menu.yml
- Was missing the API v2.3.0 topics
- Updated api_menu.yml to reflect the latest api entries form manageiq_docs/_topic_map.yml
> Updated the menus/api_menu.yml to include the v2.3.0 API documentation.

- site/_posts/2017-02-06-ansible-and-api-and-stuff.md
> Blog post for LWIMIQ Feb 6, 2017

- site/_posts/2017-02-10-love-is-in-the-PRs.md
Last week in ManageIQ! ❤️  
Thanks @hayesr for adding in the emojis for this one!
would appreciate some 👀  @syncrou @JPrause @imtayadeway
> LWIMIQ: Love is in the PRs

- site/_posts/2017-02-20-februarys-final-weeks-work.md
Oh hey guyz, don't be mental, its my first :hocho:
@syncrou @JPrause @imtayadeway ya'll seem to be da :eyes: that make all things :godmode:
> LWIMIQ for 2-21

- site/_posts/2017-02-27-embedding-ansible-additions.md
Another LWIMIQ post!
This is the first blog post I have written in a long while so I would appreciate any and all feedback 😄
@JPrause @syncrou @imtayadeway
> LWIMIQ embedding ansible additions edition

- site/_posts/2017-03-03-sprint-55-review-march-1-2017.html.md
Recap of Sprint 55 review with links to the meeting video and slides.
> Sprint 55 review blog post

- site/_posts/2017-02-17-sprint-54-review-february-15-2017.html.md
Recap of Sprint 54 review with links to the meeting video and slides. (back-dated)
> Sprint 54 review blog post

- site/_posts/2017-02-03-sprint-53-review-february-1-2017.html.md
Recap of Sprint 53 review with links to the meeting video and slides. (back-dated)
> Sprint 53 review blog post

- site/_posts/2017-03-12-marching-ahead-embedded-ansible.md
> 2017-03-12 LWIMIQ

- site/_posts/2017-03-31-sprint-57-review-march-29-2017.html.md
Recap of Sprint 57 review with links to the meeting video and slides.
> Sprint 57 review blog post

- site/_data/download_types.yaml
- site/_posts/2017-04-03-Announcing-Fine-Beta-Release.html.md
- site/download/index.md
Updating Fine Beta download file sizes with most recent info from John; add Google Analytics to download links in Fine Beta blog post to track downloads; update Vagrant link from Euwe to Fine.
> Edits to Fine Beta downloads

- site/_posts/2017-04-07-blood-fire-manageiq.md
> 2017-04-07 LWIMIQ post

- site/_posts/2017-04-17-Fine-tuning-Fine.md
@JPrause @cybette Please review.
Thanks.
> Fine-tuning Fine BLOG post 04/18/2017

- site/_posts/2017-04-17-Fine-tuning-Fine.md
@JPrause @cybette I happened to notice in http://manageiq.org/blog/2017/04/Fine-tuning-Fine/ that the PR links were not showing up correctly.
Hence I have created this PR to fix the links.
I was using the Github `Preview` feature before which shows the links just fine, probably why I didn't realize that there was an issue.
While at it, I've also shortened the title to simply `And Finally . . . Fine-tuning Fine`
Sorry about this PR.
Rookie blogger mistake I suppose :)
> Fix Title and PR links in site/_posts/2017-04-17-Fine-tuning-Fine.md

- site/_posts/2017-04-24-Squashing-Bugz.md
@syncrou @cybette @imtayadeway @JPrause please review
> LWIMIQ by Harpreet, 04-24-2017

- site/_posts/2017-05-01-lovecraftian_last_week.html.md
- site/blog/2017-05-01-llw/code.html.md
- site/blog/2017-05-01-llw/grimoire.html.md
- site/blog/2017-05-01-llw/pause.html.md
- site/blog/2017-05-01-llw/review.html.md
- site/blog/2017-05-01-llw/weekly.html.md
Lovecraft + Choose Your Own Adventure! Enjoy.
> Lovecraftian Last Week in MIQ

- site/_posts/2017-05-16-lwimiq-words.md
Words - named after the thing I was out of :).
So yeah, this could use some imaginative intro and outro, but...
> LWIMIQ 2017-05-16: Words

- site/_posts/2017-05-12-sprint-60-review-may-10-2017.html.md
Recap of Sprint 60 review with video recording, slides, and changelog.
> Sprint 60 review blog post

- site/_posts/2017-05-23-flurry-of-activity.md
Emojis are fun ✨ 
cc: @imtayadeway @syncrou @AllenBW
> lwimiq 5-23

- site/_includes/footer.html
- site/security.md
Initial security page for the ManageIQ site with basic contact information.
> Add Security Page

- site/community.md
updating the Sprint reviews section of community page with new link
> New Bluejeans link for Sprint review meetings

- site/_posts/2017-05-26-gearing-up-for-Gaprindashvili-and-beyond.md
> 2017-05-26 LWIMIQ

- site/_posts/2017-05-26-gearing-up-for-Gaprindashvili-and-beyond.md
> 2017-05-26 LWIMIQ - fix title

- lib/miq/lwimiq.rb
> add other providers to lwimiq generator

- site/_posts/2017-06-18-The-UI-is-the-thing.md
Last Week in ManageIQ blog post for June 19, 2017.
> Blog post for LWIMIQ June 19, 2017

- site/_posts/2017-06-26-migrating-migrations.md
@djberg96 and @JPrause  Please review
> Blog post for LWIMIQ June 26, 2017.

- Dockerfile
Currently images are built from `ehayes/centos72-ruby23`, `ehayes/nginx`, and `ehayes/manageiq_org_base`. This uses only `manageiq/ruby` and begins to move the Docker image to the official ManageIQ org on Docker hub.
> Base Docker image on manageiq/ruby and combine separate images into one.

- site/_assets/css/_features.scss
- site/_includes/features.html
This PR makes the Features section responsive for small devices.
Before:
After:
> Make "Features" section of homepage responsive

- Gemfile.lock
New Bundler version will cause this diff for anyone bundling with the newest version.
> Bundler 1.15.1 lockfile changes

- site/_posts/2017-07-18-kicking-off-the-summer-edition.md
> LWIMIQ July 18th

- site/_posts/2017-08-01-limericks-week-in-miq.md
> Limericks Week in MIQ

- site/_data/releases.yaml
- site/_posts/2017-08-03-Announcing-Fine-3.html.md
For when we have completed smoke testing Fine-3
> Announcement for Fine-3 release

- site/_posts/2017-08-11-back-to-basics.md
Back to basics with this week's edition of last week in manageiq 
cc: @JPrause 
👀 appreciated @syncrou @imtayadeway
> lwimiq 08 15 back to basics

- site/_posts/2017-08-29-where-have-all-the-cow-wranglers-gone.md
@JPrause @imtayadeway @syncrou 👋 📖 
OK added something to the gitignore... if this is 🙅‍♂️ will 🔪 it!
> Adds 8-29 blog post

- site/_posts/2017-08-29-where-have-all-the-cow-wranglers-gone.md
@juliancheal your 👁 belongs in a 🗼 #notsauron
> Hotfix, addressing bullet spacing

- site/_posts/2017-09-11-changelogs.md
>  [LWIMIQ] Why Changelogs - Cause all the Cool Kids Do It

- site/_posts/2017-09-13-manageiq-community-survey.html.md
Here's a short post for the short survey. Hope both are sweet enough :stuck_out_tongue:
> ManageIQ Community Survey

- site/_posts/2017-09-19-lwimiq-all-hands-busy.md
Here's my first lwimiq entry. Sorry for my tardiness. 
@JPrause @jntullo @syncrou @imtayadeway be kind rewind. I mean review. :stuck_out_tongue_winking_eye:
> [LWIMIQ] All Hands Busy

- site/_posts/2017-09-25-last-week-of-summer.md
> 2017-09-25 LWIMIQ

- site/_posts/2017-09-25-last-week-of-summer.md
Fixed formatting in 2017-09-25 LWIMIQ
> Fix formatting in 2017-09-25 LWIMIQ

- site/docs/api.md
- site/docs/get-started/where-to-go-from-here.md
- site/docs/index.md
[skip ci]
This fixes https://github.com/ManageIQ/manageiq.org/issues/581
> Fix link to REST API reference docs

- site/_posts/2017-09-13-manageiq-community-survey.html.md
Removing embedded survey and link since the survey is closed
@JPrause @Fryguy please review and merge
> Close community survey

- site/docs/get-started/basic-configuration.md
> Fix a typo

- site/_posts/2017-10-06-h-release-rearchitecture.md
> H-release Rearchitecture blog post

- site/_posts/2017-10-16-how-was-your-last-week.md
@JPrause 
@miq-bot assign @cybette
> fixes and removing tags in lwimq2017-10-16

- site/_data/releases.yaml
- site/_posts/2017-10-25-Announcing-Fine-4.html.md
> Announcement for Fine-4 release

- site/_posts/2017-10-25-api-contributors-guide.md
Breaking down the addition of a new collection / subcollection into a blog post.
fact check @imtayadeway ? 
cc: @martinpovolny @abellotti @himdel
> API Contributor's guide

- site/_posts/2017-10-18-vote-on-naming-h-release.html.md
> Names for H-Release naming

- site/_posts/2017-11-13-if-on-a-jersey-night.md
> Adds 11-13 post

- site/_data/download_types.yaml
- site/download/index.md
Vagrant link for Gaprindashvili was pointing to the wrong box, and download sizes for the beta release is updated.
@Fryguy please review and merge.
> Fix download link and sizes for G-Beta1

- site/_posts/2017-11-21-announce_h_name.html.md
@Fryguy please review and merge.
> Blog post to announce the Hammer release name

- site/_posts/2017-10-18-vote-on-naming-h-release.html.md
- site/_posts/2017-11-21-announce_h_name.html.md
> Fix Hammer's first name

- site/_posts/2017-11-27-bugs-in-fix-out.md
@JPrause @cybette please take a look
> LWIMIQ blog for 11272017

- site/_data/releases.yaml
- site/_posts/2017-11-30-Announcing-Gaprindashvili-Beta2.html.md
> Gaprindashvili Beta2 Announce

- site/_posts/2017-12-05-last-week-in-manageiq-fixing-bugs.html.md
New blogpost `LWIMIQ - fixing bugs`
> LWIMIQ - fixing bugs

- site/_posts/2017-12-11-bug-workshop.md
> LWIMIQ 12-11

- site/_data/releases.yaml
- site/_posts/2017-12-13-Announcing-Gaprindashvili-RC.html.md
> Release announcement for Gaprindashvili RC1

- site/_posts/2017-12-18-Look-back-and-reflect.md
@JPrause Please review this year-end special edition of LWIMIQ.
Thanks.
> 2017: Rear-View Mirror Reflections

- .gitignore
- dot-env-example
- lib/miq.rb
- site/_config.yml
- site/_data/menus/ref_menu_gaprindashvili.yml
- site/docs/reference/index_gaprindashvili.md
@epwinchell I was able to generate it properly after @hayesr helped me in #625, please check it out.
> Add required files for enabling the gaprindashvili docs generation

- site/_posts/2018-02-01-first-mast-lonth.html.md
> Add January blog post

- site/_data/releases.yaml
- site/_posts/2018-03-06-Announcing-Gaprindashvili-2.html.md
- site/_posts/2018-05-06-Announcing-Gaprindashvili-2.html.md
> Gaprindashvili-2 announcement

- site/_posts/2018-04-04-quandries.md
> Add March post :)

- site/_posts/2018-04-04-last-week-in-manageiq-quandries.md
... yaml parsing is difficult.
> Adds quotes to title

- site/_posts/2018-05-02-last-week-in-manageiq-two-mcminutes.md
> Add April post

- site/_posts/2018-05-02-last-week-in-manageiq-two-mcminutes.md
> Change lwimiq to last month

- site/_data/releases.yaml
- site/_posts/2018-05-14-Announcing-Gaprindashvili-3.html.md
> Announement for Gaprindashvili-3 release

- site/_posts/2018-06-04-yet-another-last-month-in-manageiq.md
> Add may post

- site/_posts/2018-06-27-sea-shanty.md
early cause I'm on PTO next week n' stuff
🎉
> Add July post 

- site/_posts/2018-07-09-vote-on-naming-i-release.html.md
- site/_posts/2018-07-16-vote-on-naming-i-release.html.md
> i-names and background info

- site/_posts/2018-07-09-vote-on-naming-i-release.html.md
> Correct spelling for Ildar

- site/_data/releases.yaml
- site/_posts/2018-07-12-Announcing-Gaprindashvili-4.html.md
> Announcement for Gaprindashvili-4

- site/_posts/2018-07-09-vote-on-naming-i-release.html.md
> Fix name for Ivanchuk

- site/_posts/2018-07-23-announce_i_name.html.md
> ManageIQ I-Release name anncouncement

- site/_posts/2018-10-02-last-month-in-miq-building-a-blog-post.md
> Add Sept blog post

- site/_data/download_types.yaml
Needs https://github.com/ManageIQ/manageiq-appliance-build/pull/289 to be merged first.
> Azure, HyperV and EC2 images are now compressed

- site/docs/get-started/docker.md
> Gaprindashvili and later docker images don't need to run privileged

- site/_data/releases.yaml
- site/_posts/2018-10-29-Announcing-Hammer-Beta2.html.md
> Hammer Beta2 Announcement

- site/_posts/2018-10-29-last-month-in-miq-to-queue-or-not-to-queue.md
> Add oct post

- site/_data/releases.yaml
- site/_posts/2018-11-02-Announcing-Gaprindashvili-6.html.md
> Announcement for Gaprindashvili-6

- site/_data/releases.yaml
- site/_posts/2018-12-03-Announcing-Hammer-RC2.html.md
> Announcement for Hammer RC2

- site/_config.yml
Peter McGowan has an update to the automation book.
@JPrause please review
> Update URL for Automation book

- site/_data/releases.yaml
- site/_posts/2018-12-17-Announcing-Gaprindashvili-7.html.md
> Announcement for Gaprindashvili-7

- site/_posts/2018-12-12-reinventing-the-proxy.md
Sorry, one extra letter :cry: 
@miq-bot assign @cybette
> Fix typo in the proxy blogpost so the code example will make sense

- site/_data/download_types.yaml
> Add libvirt to download screen

- site/community.md
> Fix Broken Facebook button in Connect section

- .gitignore
- dot-env-example
- lib/miq.rb
- site/_config.yml
- site/_data/menus/ref_menu_hammer.yml
- site/docs/reference/index_hammer.md
Relates to: https://github.com/ManageIQ/manageiq.org/pull/635
Before:
After:
> Add required files to enable Hammer doc generation

- site/_data/releases.yaml
- site/_posts/2019-02-07-Announcing-Hammer-2.md
> Announcement for Hammer-2

- site/_data/releases.yaml
- site/_posts/2019-03-06-Announcing-Hammer-3.md
> Announcement for Hammer-3 release

- site/_data/menus/ref_menu_euwe.yml
- site/_data/menus/ref_menu_fine.yml
- site/_data/menus/ref_menu_gaprindashvili.yml
- site/_data/menus/ref_menu_hammer.yml
- site/_data/menus/ref_menu_latest.yml
- site/docs/reference/index.md
- site/docs/reference/index_euwe.md
- site/docs/reference/index_fine.md
- site/docs/reference/index_gaprindashvili.md
- site/docs/reference/index_hammer.md
- site/docs/reference/index_latest.md
This PR added Authentication to the table of contents for each release
> Update Reference TOC with Authentication

- site/_data/menus/guides_menu.yml
> Add UI to Dev Guides Menu

- site/_data/releases.yaml
- site/_posts/2019-03-29-Announcing-Hammer-4.md
> Hammer-4 announcement

- site/_posts/2019-03-31-lmimiq-multiple-automates-in-flight.html.md
> March blog post

- site/_posts/2019-03-31-lmimiq-multiple-automates-in-flight.html.md
Take two? 
@cybette thanks and sorry
> Redoing numbering, yarps

- site/_posts/2019-03-31-lmimiq-multiple-automates-in-flight.html.md
Hi @cybette! Happy Monday! I'm so sorry.
> Blog post march take three :) 

- site/_data/github_repos.yaml
> Update repos on community page

- site/_data/releases.yaml
- site/_posts/2019-04-23-Announcing-Hammer-5.md
> Announcement for Hammer-5 release

- site/docs/get-started/add-a-provider.md
* Correct AWS name (Services, not Server)
* Google Cloud Platform is the proper product name
> Minor documentation copy edit

- site/_data/releases.yaml
- site/_posts/2019-05-21-Announcing-Hammer-6.md
> Announcement for Hammer-6 release

- site/_posts/2019-01-09-manageiq-provider-operations-with-ansible-xlab.md
Because we now have standalone blog for XLAB Steampunk, we would like to
update these links to point to the most up-to-date content
> Fix links to XLAB Steampunk blog

- site/_data/releases.yaml
- site/_posts/2019-06-10-Announcing-Hammer-7.md
> Announcement for Hammer-7 release

- site/_data/releases.yaml
- site/_posts/2019-07-02-Announcing-Hammer-8.md
> Announce Hammer-8 release

- site/_posts/2019-07-09-Red-Hat-IBM-and-ManageIQ.md
@Fryguy @epwinchell @JPrause please review
> Message to the community about IBM's acquisition of Red Hat

- site/_data/releases.yaml
- site/_posts/2019-07-23-Announcing-Hammer-9.md
> Announce Hammer-9 release

- site/_data/releases.yaml
- site/_posts/2019-07-26-Announcing-Icanchuk-Beta1.html.md
> Announcement for Ivanchuk Beta1 release

- site/_posts/2019-07-29-vote-on-naming-j-release.html.md
> Chessmasters for the J-Name Release

- site/_posts/2019-08-12-announce_j_name.html.md
> Announce J release name

- site/_data/releases.yaml
- site/_posts/2019-08-09-Announcing-Ivanchuk-Beta2.html.md
- site/download/index.md
> Announcement for Ivanchuk Beta2

- site/_data/releases.yaml
- site/_posts/2019-08-12-Announcing-Hammer-10.md
> Announcement for Hammer-10

- site/_posts/2019-08-20-announce_rest_client_vulnerability.html.md
Announce the rest-client vulnerability and status of ManageIQ releases
> Announcement about rest-client vulnerability

- site/_data/releases.yaml
- site/_posts/2019-08-26-Announcing-Ivanchuk-RC1.html.md
> Announcement for Ivanchuk RC1

- site/_data/releases.yaml
- site/_posts/2019-09-09-Announcing-Hammer-11.md
> Announcement for Hammer-11

- site/community.md
> Switch to updated dial-in number

- site/_data/download_types.yaml
> Update file sizes for nightlies

- site/_posts/2019-12-06-introducing-new-provider-microsoft-azure-stack.md
We failed to invite readers to test the new provider in our previous
commit. This one fixes this with a reference to the Ivanchuk download
page and Steampunk contact.
> Add Azure Stack CTA

- site/docs/get-started/index.md
Fixes https://github.com/ManageIQ/manageiq.org/issues/620
> Mention manageiq-pods in the getting started page

- site/_data/releases.yaml
- site/_posts/2019-12-13-Announcing-Ivanchuk-2.md
@mfeifer please review, thanks!
> Announcement for Ivanchuk-2

- site/_posts/2020-02-13-Embedded-Ansible-Part-3-Ansible-In-An-Automation-Workflow.md
Peter wrote 4 articles about embedded Ansible work in CFME 4.5 that were intended for posting on the CloudFormsNow site but aren't going to all get posted and so I was asked to put them here since it's a shame to waste the research and time that went into this effort. They're great, and we should post them, part three.
Part one: https://github.com/ManageIQ/manageiq.org/pull/796
Part two: https://github.com/ManageIQ/manageiq.org/pull/797
> Add embedded ansible post three

- site/_posts/2020-02-12-Embedded-Ansible-Part-1-Built-In-Roles.md
- site/_posts/2020-02-12-Embedded-Ansible-Part-2-Passing-Parameters-Into-A-Playbook.md
- site/_posts/2020-02-13-Embedded-Ansible-Part-3-Ansible-In-An-Automation-Workflow.md
Things and stuff in double curly braces are empty unless they have raw tags even inside a code block :( 
@cybette please review, thanks
> Add raw tags so the things show up right

- site/_posts/2020-02-13-Embedded-Ansible-Part-4-Working-With-State-Machines.md
Peter wrote 4 articles about embedded Ansible work in CFME 4.5 that were intended for posting on the CloudFormsNow site but aren't going to all get posted and so I was asked to put them here since it's a shame to waste the research and time that went into this effort. They're great, and we should post them, part the last.
Part one: https://github.com/ManageIQ/manageiq.org/pull/796
Part two: https://github.com/ManageIQ/manageiq.org/pull/797
Three: https://github.com/ManageIQ/manageiq.org/pull/798
> Add embedded post four

- site/_posts/2020-02-12-Embedded-Ansible-Part-2-Passing-Parameters-Into-A-Playbook.md
@cybette sorry, ugh, one more time
> Add one more set of raw tags for formatting

- site/_data/menus/api_menu.yml
Update api menu with references/conversion_hosts and transformation_mappings
> Update api menu

- site/_data/menus/start_menu.yml
- site/docs/get-started/index.md
- site/docs/get-started/kubernetes.md
As requested in https://github.com/ManageIQ/manageiq.org/pull/818#issuecomment-606843442
cc @chessbyte @Fryguy
> Add a getting started guide for kubernetes

- site/_data/download_types.yaml
- site/_plugins/download_filter.rb
- site/download/index.md
Fixes https://github.com/ManageIQ/manageiq.org/issues/694
Here is a snapshot of the resulting screen (partial view):
> Compute url file sizes for downloads

- site/_assets/css/_page.scss
- site/_includes/docs/doc_tabs.html
- site/_includes/head.html
Add custom Google search to Documentation 
Issue: https://github.com/ManageIQ/manageiq.org/issues/729
> Add documentation search

- site/_data/menus/ref_menu_latest.yml
Fixes https://github.com/ManageIQ/manageiq_docs/issues/1333
> Add all available installation guides

- lib/miq/guides.rb
> Ignore bin directory in guides

- .gitignore
trivial but...
before:
```
git status
Untracked files:
(use "git add <file>..." to include in what will be committed)
.asset-cache/
```
after:
```
On branch gitignore
nothing to commit, working tree clean
```
> don't show differences in asset cache

- site/_data/download_types.yaml
- site/_data/releases.yaml
- site/_includes/download/release_table.md
- site/_plugins/download_filter.rb
- site/download/index.md
The page is basically unchanged except for the addition of Kubernetes and OpenShift in the prerelease and nightly sections.
> Cleanup downloads

- .gitignore
- exe/console
- exe/miq
- lib/miq.rb
- lib/miq/legacy_ref_docs.rb
- lib/miq/ref_page.rb
- lib/miq/ref_versions.rb
- lib/miq/site.rb
- site/_assets/css/_docs.scss
- site/_config.yml
- site/_data/menus/api_menu.yml
- site/_data/menus/guides_menu.yml
- site/_data/menus/ref_menu_euwe.yml
- site/_data/menus/ref_menu_fine.yml
- site/_data/menus/ref_menu_gaprindashvili.yml
- site/_data/menus/ref_menu_hammer.yml
- site/_data/menus/ref_menu_jansa.yml
- site/_data/menus/ref_menu_latest.yml
- site/_data/menus/start_menu.yml
- site/_layouts/doc_page.html
- site/_plugins/download_filter.rb
- site/docs/get-started/vagrant.md
- site/docs/reference/index_jansa.md
- test/lib/miq/ref_versions_test.rb
Depends on https://github.com/ManageIQ/manageiq_docs/pull/1439
> Convert website to do a Jekyll build for manageiq_docs

- lib/miq.rb
- site/_data/menus/ref_menu_jansa.yml
- site/_data/menus/ref_menu_latest.yml
- test/lib/miq/ref_versions_test.rb
Depends on:
Fixes https://github.com/ManageIQ/manageiq-documentation/issues/1432
> Update jansa to markdown

- site/_data/releases.yaml
- site/_posts/2020-07-29-Announcing-Jansa-Release-Candidate.md
If I missed any enhancements since the Jansa Beta release, please let me know and I will add it to this PR.
> Announcing ManageIQ Jansa Release Candidate

- site/_data/menus/ref_menu_latest.yml
Add the [Capabilities Matrix](https://github.com/ManageIQ/manageiq-documentation/pull/1474) to the website under Documentation => User Reference => Reference section
> Add Capabilities Matrix

- site/_data/releases.yaml
- site/_posts/2020-08-17-Announcing-Ivanchuk-2-And-Jansa-1-RC2.md
@chessbyte @simaishi Please review.
> Announce ivanchuk-7 and jansa-1-rc2

- site/community.md
- site/roadmap.html
This way, in presentations, you can refer to the roadmap from https://manageiq.org/roadmap
> Add roadmap

- site/_posts/2020-09-03-oidc-auth-api-usage.md
Initial commit of API usage when configured with OIDC
> Add Using the API with OIDC blog post

- dot-env-example
- site/_data/releases.yaml
- site/_posts/2020-09-22-manageiq-jansa-ga-announcement.md
@chessbyte @simaishi Please review.
> Jansa GA Announcement

- site/_posts/2020-09-22-manageiq-jansa-ga-announcement.md
> Fix bad links

- site/_includes/footer.html
Partially fixes https://github.com/ManageIQ/manageiq.org/issues/491
@miq-bot add_reviewer @romanblanco 
@miq-bot add_reviewer @epwinchell
> Add an "Edit this page" button for non-documentation pages

- site/_data/menus/ref_menu_latest.yml
Depends On: https://github.com/ManageIQ/manageiq-documentation/pull/1486
> Link to installing on Kubernetes

- site/_data/menus/ref_menu_latest.yml
Depends on https://github.com/ManageIQ/manageiq-documentation/pull/1482
> Link to Installing on IBM Cloud

- site/_data/releases.yaml
- site/_posts/2020-10-30-Announcing-Jansa-2.md
> Announcing Jansa-2 blog post

- site/_posts/2020-09-21-troubleshooting-containerized-oidc.md
This PR adds instructions for bumping the httpd log level to debug.
> Add how to adjust httpd log level

- site/_data/releases.yaml
- site/_posts/2020-12-04-Announcing-Kasparov-Alpha.md
> Announcing Kasparov Alpha

- site/_data/releases.yaml
- site/_posts/2021-01-18-Announcing-Kasparov-Beta-Jansa-3-And-Ivanchuk-8.md
WIP until the builds are complete and smoke tested.
> Announcing Kasparov Beta, Jansa-3, and Ivanchuk-8

- site/_data/releases.yaml
- site/_posts/2021-02-04-manageiq-kasparov-ga-announcement.md
> Release Kasparov GA

- site/_data/download_types.yaml
- site/_data/platforms.yaml
> Add IBM Cloud download and supported platform

- .gitignore
- dot-env-example
- lib/miq.rb
- site/_config.yml
- site/docs/reference/index_kasparov.md
@chessbyte Please review. When we released Kasparov, I forgot the docs section on the website.
> Add kasparov docs

- site/_data/releases.yaml
- site/_posts/2021-04-26-Announcing-Lasker-Beta.md
> Announcing Lasker Beta

- .gitignore
- lib/miq.rb
- site/_config.yml
- site/_data/releases.yaml
- site/_posts/2021-07-20-cve-2021-32756-kasparov-2-jansa-4.md
- site/_posts/2021-07-20-manageiq-lasker-ga-annoucement.md
- site/docs/reference/index_lasker.md
@bdunne Please let me know when all of the builds are ready and we can merge this.
> Release Lasker-1, Kasparov-2, and Jansa-4

- site/download/index.md
Based on https://github.com/ManageIQ/manageiq-documentation/pull/1589#issuecomment-900519685
> Add a link to the upgrade documentation

- site/_data/menus/api_menu.yml
> Add link to reconfigure_vm.html API example

- site/_data/releases.yaml
- site/_posts/2021-12-16-Announcing-Morphy-Beta.md
I feel like more was done on the core side (@jrafanie @kbrock), UI side (@kavyanekkalapu), and non-IBM provider side (@agrare) and maybe it just wasn't reflected in the roadmap (like splitting out the morphy UI form changes into their own issue)?  Or perhaps things weren't split out into a dedicated issue?  Or maybe I'm just confusing it with all of the Najdorf work!  Can you all take a look and verify that the major highlights for morphy are correct and if not, let's work on getting those onto the roadmap and ultimately here.
WIP because we need to wait for the build to be released.  cc @bdunne
> Add Blog post and release for morphy-1-beta1

- site/_layouts/default.html
Fixes #1055
Fixes #1056 
Fixes #1057
> Update jquery version from 3.1.0 to 3.6.0

- .github/workflows/ci.yaml
Goes with https://github.com/ManageIQ/manageiq.github.io/pull/13
> Get PR Number into payload

- .gitignore
- lib/miq.rb
- lib/miq/ref_versions.rb
- site/_config.yml
- site/_data/releases.yaml
- test/lib/miq/ref_versions_test.rb
To be merged when we release morphy and merged with #1067
> Release morphy-1

- site/_data/sprints/gh_186.yaml
> Add Sprint 186 stats

- site/_sprints/187.md
> Start Sprint 187

- site/_config.yml
- site/docs/automation.md
> Fix automate book links

- site/_data/sprints/gh_187.yaml
- site/_sprints/188.md
> Sprint 187 stats and start Sprint 188

- site/_sprints/187.md
> Add Sprint 187 slides and recording

- site/_data/sprints/gh_189.yaml
- site/_sprints/189.md
- site/_sprints/190.md
> Sprint 189 stats and start Sprint 190

- site/_data/sprints/gh_190.yaml
- site/_sprints/190.md
- site/_sprints/191.md
> Sprint 190 stats and start Sprint 191

- site/_data/sprints/gh_191.yaml
- site/_sprints/191.md
- site/_sprints/192.md
> Sprint 191 stats and start Sprint 192

- .gitignore
- lib/miq.rb
- site/_config.yml
- site/_data/releases.yaml
- site/_posts/2022-07-18-manageiq-najdorf-ga-announcement.md
- site/docs/reference/index_najdorf.md
> Announcing Najdorf release

- site/_posts/2016-08-11-publishing-an-ansible-job-template-as-a-service-in-cloudforms.md
- site/_posts/2016-09-20-notify-vm-owner-of-upcoming-retirement.md
- site/_posts/2018-01-24-automating-clouforms-appliance-deployment-with-ansible.md
- site/_posts/2018-04-31-ansible-custom-buttons-in-cloudforms-part-2-creating-the-button.md
@jrafanie or @chessbyte Please review.
> Fix a few more invalid blog tags

- site/_plugins/blog_tags.rb
- site/_posts/2017-09-27-container-management-with-cloudforms.md
- site/_posts/2017-10-04-container-management-with-cloudforms-operational-efficiency.md
- site/_posts/2017-10-11-container-management-with-cloudforms-service-health.md
- site/_posts/2017-10-18-container-management-with-cloudforms-security-and-compliance.md
- site/_posts/2017-10-25-container-management-with-cloudforms-financial-management.md
- site/_posts/2018-07-09-tips-fom-the-tour-part-1-global-dashboard-and-integrations.md
This PR also fixes some tags that are effective duplicates of other tags.
---
Requested in https://github.com/ManageIQ/manageiq.org/pull/1109#issuecomment-1191593862 (cc @chessbyte)
I started looking into sorting by tag count, so popular tags would bubble to the top, but it's a lot more complicated than I expected, so I'm punting on that for now.  At least now the tags don't appear random.
> Sort tags alphabetically

- site/docs/reference/index_morphy.md
@bdunne Please review.  This was somehow left out of the morphy release commit.
> Add missing index file for morphy user ref docs

- site/_data/sprints/gh_192.yaml
- site/_sprints/192.md
- site/_sprints/193.md
> Sprint 192 stats and start Sprint 193

- site/_data/sprints/gh_193.yaml
- site/_sprints/193.md
- site/_sprints/194.md
> Sprint 193 stats and start Sprint 194

- site/_data/sprints/gh_194.yaml
- site/_sprints/194.md
- site/_sprints/195.md
> Sprint 194 stats and start Sprint 195

- site/_data/sprints/gh_195.yaml
- site/_sprints/195.md
- site/_sprints/196.md
> Sprint 195 stats and start Sprint 196

- site/_data/sprints/gh_196.yaml
- site/_data/sprints/gh_197.yaml
- site/_sprints/196.md
- site/_sprints/197.md
- site/_sprints/198.md
> Sprint 196 & 197 stats and start Sprint 198

- site/_data/sprints/gh_198.yaml
- site/_sprints/197.md
- site/_sprints/198.md
- site/_sprints/199.md
Also added fix for https://github.com/ManageIQ/manageiq.org/pull/1120#discussion_r997451678
@jrafanie  Please review.
> Sprint 198 stats and start Sprint 199

- site/_data/sprints/gh_199.yaml
- site/_sprints/199.md
- site/_sprints/200.md
> Sprint 199 stats and start Sprint 200

- site/_data/sprints/gh_200.yaml
- site/_sprints/200.md
- site/_sprints/201.md
> Sprint 200 stats and start Sprint 201

- site/_sprints/200.md
@jrafanie Please review.  For some reason I had to reupload because the original upload failed.
> Fix link to Sprint 200 slides

- .github/workflows/ci.yaml
> Update tokens for ci workflow

- site/_data/sprints/gh_202.yaml
- site/_sprints/202.md
- site/_sprints/203.md
> Sprint 202 stats and start Sprint 203

- .gitignore
- lib/miq.rb
- site/_config.yml
- site/_data/releases.yaml
- site/_posts/2023-01-06-manageiq-oparin-ga-announcement.md
- site/docs/reference/index_oparin.md
@bdunne Please review.  WIP until we actually release the bits.
@agrare Please review the providers.  If there are any missing items from providers not listed, please let me know.
Rendered version: https://github.com/Fryguy/manageiq.org/blob/oparin-release/site/_posts/2022-12-22-manageiq-oparin-ga-announcement.md
> Announcing Oparin release

- site/_data/sprints/gh_203.yaml
- site/_sprints/203.md
- site/_sprints/204.md
> Sprint 203 stats and start Sprint 204

- site/_data/sprints/gh_204.yaml
- site/_sprints/204.md
- site/_sprints/205.md
> Sprint 204 stats and start Sprint 205

- site/_data/sprints/gh_205.yaml
- site/_sprints/205.md
- site/_sprints/206.md
> Sprint 205 stats and start Sprint 206

- site/_data/sprints/gh_207.yaml
- site/_sprints/207.md
- site/_sprints/208.md
> Sprint 207 stats and start Sprint 208

- site/_data/sprints/gh_208.yaml
- site/_sprints/208.md
- site/_sprints/209.md
> Sprint 208 stats and start Sprint 209

- site/_assets/css/_platforms.scss
- site/_data/platforms.yaml
- site/_includes/inline_svg/platforms/oracle_cloud.svg
@agrare Please review.  I couldn't find a good Oracle Cloud logo with text, so this was the best I could do for now.
> Add Oracle Cloud to Supported Platforms

- site/_data/sprints/gh_209.yaml
- site/_sprints/209.md
- site/_sprints/210.md
> Sprint 209 stats and start Sprint 210

- site/_data/sprints/gh_210.yaml
- site/_data/sprints/gh_211.yaml
- site/_data/sprints/gh_212.yaml
- site/_sprints/210.md
- site/_sprints/211.md
- site/_sprints/212.md
- site/_sprints/213.md
> End Sprints 210-212 and start sprint 213

- site/_posts/2018-07-23-calling-an-embedded-ansible-playbook-from-the-vm-provision-state-machine.md
- site/_posts/2020-02-12-Embedded-Ansible-Part-1-Built-In-Roles.md
- site/_posts/2020-02-12-Embedded-Ansible-Part-2-Passing-Parameters-Into-A-Playbook.md
- site/_posts/2020-02-13-Embedded-Ansible-Part-3-Ansible-In-An-Automation-Workflow.md
- site/_posts/2020-02-13-Embedded-Ansible-Part-4-Working-With-State-Machines.md
@agrare Please review.  This also had some automatic trailing whitespace fixes, so perhaps view with whitespace disabled.
> Add embedded-ansible tags to some blog posts

- site/_data/sprints/gh_217.yaml
- site/_sprints/217.md
- site/_sprints/218.md
> Sprint 217

- .gitignore
- lib/miq.rb
- site/_config.yml
- site/_data/releases.yaml
- site/docs/reference/index_petrosian.md
@bdunne Please review.  I will have the blog post soon, but thinking I'll make that a separate PR.
> Release petrosian-1

- site/_posts/2023-09-14-manageiq-petrosian-ga-announcement.md
Rendered view is here: https://github.com/Fryguy/manageiq.org/blob/petrosian_ga_blog/site/_posts/2023-09-14-manageiq-petrosian-ga-announcement.md
Depends on 
@jrafanie @agrare @bdunne Please review.
> Add Petrosian GA blog post

- site/_data/sprints/gh_218.yaml
- site/_data/sprints/gh_219.yaml
- site/_data/sprints/gh_220.yaml
- site/_data/sprints/gh_221.yaml
- site/_sprints/218.md
- site/_sprints/219.md
- site/_sprints/220.md
- site/_sprints/221.md
- site/_sprints/222.md
> Complete Sprints 218-221 and Open Sprint 222

- site/_includes/footer.html
- site/community.md
- site/docs/get-started/where-to-go-from-here.md
> Drop references to the old talk.manageiq.org

- site/_data/sprints/gh_222.yaml
- site/_data/sprints/gh_223.yaml
- site/_data/sprints/gh_224.yaml
- site/_sprints/222.md
- site/_sprints/223.md
- site/_sprints/224.md
- site/_sprints/225.md
> Sprint 222-224 closed; Sprint 225 open

- site/_sprints/222.md
- site/_sprints/223.md
- site/_sprints/224.md
> Fix links on sprints pages

- site/_data/sprints/gh_225.yaml
- site/_sprints/225.md
- site/_sprints/226.md
@jrafanie Please review.
~~WIP because slideshare is not currently uploading correctly and the URL may not be accurate until that happens.~~ EDIT: Done - and yeah the URL _was_ broken, but PR is updated to the correct one.
> Sprint 225 closed and open Sprint 226

- site/_data/sprints/gh_226.yaml
- site/_sprints/226.md
- site/_sprints/227.md
> Sprint 226 closed and open Sprint 227

- site/_data/sprints/gh_227.yaml
- site/_sprints/227.md
- site/_sprints/228.md
> Sprint 226 closed; Sprint 227 open

- site/_posts/2017-09-29-miqldap-to-sssd.md
- site/_posts/2018-01-31-troubleshooting-auth.md
- site/_posts/2018-02-01-auth-overview.md
@jrafanie Please review.  This makes it easier to find those blog posts about the miq_ldap_to_ssd tool and other ldap related blogs.  I considered an auth tag, but I think I can add that later.
> Add ldap blog tag

- site/_data/sprints/gh_228.yaml
- site/_data/sprints/gh_229.yaml
- site/_data/sprints/gh_230.yaml
- site/_sprints/228.md
- site/_sprints/229.md
- site/_sprints/230.md
- site/_sprints/231.md
Having trouble uploading to slideshare.net, so that's why those are blank. They will be updated in a future commit.
@jrafanie Please review
> Sprint 228-230 closed and open Sprint 231

- site/sprints/index.html
> Update links to more directly point to the presentations

- site/_data/sprints/gh_234.yaml
- site/_sprints/234.md
- site/_sprints/235.md
> Sprint 234 updates

- site/_data/sprints/gh_235.yaml
- site/_sprints/235.md
- site/_sprints/236.md
> Sprint 235

- site/_data/sprints/gh_236.yaml
- site/_sprints/236.md
- site/_sprints/237.md
> Sprint 236

- site/_data/sprints/gh_237.yaml
- site/_sprints/237.md
- site/_sprints/238.md
> Sprint 237

- .gitignore
- lib/miq.rb
- site/_config.yml
- site/_data/releases.yaml
- site/_posts/2024-05-29-manageiq-quinteros-ga-announcement.md
@bdunne Please review.
@agrare @jrafanie @kbrock  Please also review.
> Release Quinteros-1

- site/_data/sprints/gh_240.yaml
- site/_data/sprints/gh_241.yaml
- site/_data/sprints/gh_242.yaml
- site/_data/sprints/gh_243.yaml
- site/_data/sprints/gh_244.yaml
- site/_data/sprints/gh_245.yaml
- site/_sprints/240.md
- site/_sprints/241.md
- site/_sprints/242.md
- site/_sprints/243.md
- site/_sprints/244.md
- site/_sprints/245.md
- site/_sprints/246.md
> Sprints 240-245

- .github/workflows/ci.yaml
> Add workflow_dispatch event

- site/docs/reference/index.md
Updates to User reference page since ToC is updated via https://github.com/ManageIQ/manageiq-documentation/pull/1806
> Updated user reference page

- site/_data/sprints/gh_246.yaml
- site/_sprints/246.md
- site/_sprints/247.md
> Sprint 246

- site/_includes/footer.html
- site/_sass/_page.scss
- site/community.md
@jrafanie Please review.
Before:
After:
> Update social media links

- site/_includes/site_nav.html
> Fix minor tag close

- site/_data/sprints/gh_247.yaml
- site/_data/sprints/gh_248.yaml
- site/_data/sprints/gh_249.yaml
- site/_data/sprints/gh_250.yaml
- site/_data/sprints/gh_251.yaml
- site/_data/sprints/gh_252.yaml
- site/_data/sprints/gh_253.yaml
- site/_sprints/247.md
- site/_sprints/248.md
- site/_sprints/249.md
- site/_sprints/250.md
- site/_sprints/251.md
- site/_sprints/252.md
- site/_sprints/253.md
- site/_sprints/254.md
> Sprints 247-253

- site/_data/sprints/gh_254.yaml
- site/_data/sprints/gh_255.yaml
- site/_sprints/254.md
- site/_sprints/255.md
- site/_sprints/256.md
> Sprints 254, 255

- site/_data/sprints/gh_256.yaml
- site/_data/sprints/gh_257.yaml
- site/_sprints/256.md
- site/_sprints/257.md
- site/_sprints/258.md
> Add Sprints 256, 257

- site/_data/sprints/gh_258.yaml
- site/_data/sprints/gh_259.yaml
- site/_sprints/258.md
- site/_sprints/259.md
- site/_sprints/260.md
> Add Sprints 258, 259

- .gitignore
- lib/miq.rb
- site/_config.yml
- site/_data/releases.yaml
- site/_posts/2025-04-15-manageiq-radjabov-ga-announcement.md
- site/changelog/index.md
- site/changelog/quinteros-2-to-radjabov-1.md
> Release radjabov-1

- site/_data/sprints/gh_260.yaml
- site/_data/sprints/gh_261.yaml
- site/_sprints/261.md
- site/_sprints/262.md
> Sprints 260, 261

- site/_data/sprints/gh_262.yaml
- site/_sprints/262.md
- site/_sprints/263.md
> Sprint 262

- lib/tasks/publish_sprint.rake
> Add helper text for announcing the sprint review

- site/_data/sprints/gh_268.yaml
- site/_sprints/268.md
- site/_sprints/269.md
> Sprint 268

- site/_data/sprints/gh_269.yaml
- site/_data/sprints/gh_270.yaml
- site/_data/sprints/gh_271.yaml
- site/_sprints/269.md
- site/_sprints/270.md
- site/_sprints/271.md
- site/_sprints/272.md
> Sprints 269-271
