- Gemfile
- Gemfile.lock
- config.rb
- source/layouts/_production_only.haml
Add tracking code for Google Analytics.
Tracking is important to start measuring the efforts of various community marketing efforts we are planning.
The tracking code refers to a GA account under gjansen@redhat.com. I have the ability to add any Gmail or Google Apps account.
If it's more appropriate, I'm also happy to transfer the GA account to John Mark as the community manager.
> Add Google Analytics tracking

- source/community/install-from-source.html.md
Without g++ installed, i got this error during `bundle install` command:
make "DESTDIR="
compiling kb.cpp
`make: g++: Command not found`
Makefile:215: recipe for target 'kb.o' failed
make: *** [kb.o] Error 127
...
An error occurred while installing eventmachine (1.0.6), and Bundler cannot
continue.
Make sure that `gem install eventmachine -v '1.0.6'` succeeds before bundling
> g++ is prerequisite for installing eventmachine gem

- source/community/index.html.haml
Perhaps talk.manageiq.org changed URLs?
> fixed an incorrect link for feature suggestions (404 on talk)

- source/community/install-from-source.html.md
Fixed markdown that was causing wrong highlighting on '[Install from source](http://manageiq.org/community/install-from-source/)' page.
Example:
> Fixed markdown on 'Install from source' page

- source/community/install-from-source.html.md
- changed bundler version according https://github.com/ManageIQ/manageiq/pull/3390
- removed `rake build:shared_objects` as it's not used anymore https://github.com/ManageIQ/manageiq/pull/3293
- edited movement in directories after rerooted vmdb https://github.com/ManageIQ/manageiq/pull/3363
- changed postgresql database inialization command
> Updated manual after rerooted vmdb

- source/index.html.haml
The website lists more partners than the original founders, hence this removal.
> as more partners were added since the founding, s/partners//

- source/documentation/getting-started.html.md
The illustration is labelled a-j, but the key is 1-10. This change makes
the key use the same type (lower alpha).
> Fix VM pages illustration key

- source/depot/extensions-info.rb
It seems that the growth of the project make the builder hit
some query limit, but I would need more information to verify
that hypothesis.
> Add a better error message that tell what user is causing trouble

- data/releases.yml
- source/blog/2015-12-05-manageiq-capablanca-azure-containers-self-service-ui.html.md
- source/download/index.html.haml
I don't know how to re-point the `*-stable.*` filenames on the download server, so I went with a plan B... but I don't particularly like them anyway: it means people can't use their downloaded filename as a clue to which version they have.
> Release Capablanca

- source/layouts/_footer.haml
Fixes #229, without introducing a shell injection.
In passing, don't bother searching the complete history of the file when we just want to know one date.
> Don't leave dangling processes

- README.md
I'm not entirely familiar but I believe the submodules included in this project are intended to be cloned to run it locally. This changes the command given to include `--recursive` to clone the guides and remove errors such as this one when following the steps outlined in README:
```
middleman-core/sitemap/extensions/proxies.rb:46:in `proxied_to_resource': Path documentation/development/index.html proxies to unknown file documentation/development/README.html:[] (RuntimeError)
```
> Include submodules in clone command (README)

- data/deploy_types.yml
- source/download/index.html.haml
For now, just making the download links point to ovirt.  A better fix is
to probably create either a symlink or a virtual proxy for rhev links,
but that will require more investigation.
> Fix download links for RHEV.

- source/community/index.html.haml
- source/community/licensing-faq.html.md
- source/documentation/faq.html.md
Given the merging of https://github.com/ManageIQ/manageiq/pull/7481
this updates and simplifies the statements on the ManageiQ website concerning licensing.
> Update information on ManageIQ licensing

- source/index.html.haml
- source/stylesheets/lib/site.sass
- source/summit/index.html.haml
Changes:
1. adding a visible summit link for visitors to the front page of manageiq.org
2. updating the Program/CFP section to give a better idea of possible topics
3. extending the CFP deadline by a week based on feedback/discussions
> Add summit teaser on main page + update CFP description and extension

- source/stylesheets/lib/site.sass
- source/summit/index.html.haml
Update the Program section of the summit page: remove info about CFP that has ended, and add the 2-day event agenda.
> Add agenda to ManageIQ design summit page

- source/blog/2016-07-26-last-week-in-manageiq-faster-reports-cloud-networks-and-more.md
Adding the first *This Week in ManageIQ* post.
This first post has been loosely based on the format used in *This Week in Rails*, which seems to work well. Having said that, I wasn't quite sure how this would come together when I started, so I'm totally open to changing anything about this - any feedback welcome. I want this to reflect well on the team and the community.
If there were any stories from this week you felt were a glaring omission from this issue, please let me know and I will add it in. Likewise I'm not precious about keeping anything.
Here are some observations I had on making this first post:
* I actually had no idea we were so productive. Going through 109 PRs from the last week was more work than I anticipated! It would be great if we could pool resources as editors to …
> Add last week in ManageIQ 2016-07-26

- data/authors.yml
- source/blog/2016-09-05-last-week-in-manageiq-api-refactor-observables.html.md
Our newest last week 09/05 - API refactor, Observables and more..
> Last week in ManageIQ 2016-09-05

- site/docs/get-started/add-a-provider.md
- site/docs/get-started/basic-configuration.md
- site/docs/get-started/cloud.md
- site/docs/get-started/provision-machine.md
- site/docs/get-started/review-provider.md
Adding {:.img-responsive} at the end of images tag them as responsive, allowing the documentation to be seen in any size of screen.
> adding tags for responsive images

- site/download/index.md
Links to manageiq.org/download won't work on the new site, this change points directly to releases.manageiq.org instead.
> Link downloads to releases.manageiq.org

- Dockerfile
Set the JEKYLL_ENV var in the Docker build to allow for contextual including of things like Google Analytics.
> Production ENV var for Jekyll

- site/docs/index.md
Adds a missing link to API docs
> Link to API docs from documentation overview page

- site/docs/index.md
> Fix API Docs link

- site/download/index.md
This is necessary to display the pre-release download section.
Concerns #391
> Add pre-release section for Euwe

- site/_includes/head.html
Page titles are now like "ManageIQ - Get Started". It results in nicer
summaries in Google search results.
> Prefix page title with site title.

- site/_config.yml
- site/_data/menus/start_menu.yml
- site/_includes/docs/top_menu_items.html
- site/docs/automation.md
- site/docs/get-started/concepts.md
- site/docs/get-started/index.md
This change enables training slashes for directories, and no trailing slashes
for files. The way it ought to be!
It now correctly marks TOC items under "Get started" as active. And this also
centralizes a few permalink and doc_group settings into _config.yml.
> Be consistent with trailing slashes.

- site/_assets/css/_docs.scss
- site/docs/get-started/cloud.md
- site/docs/get-started/docker.md
- site/docs/get-started/index.md
- site/docs/get-started/vagrant.md
The image styles are currently a crude hack. Someone with CSS experience should
have a look at this (Eric that may be you :).
The main changes are:
* Don't explain how to get started with the three options. Assume people that select an option already have Vagrant, Docker, or Google.
* Focus Vagrant on Windows and Mac users, and Docker on Linux users. I expect this to be the main audiences for these options.
* Since we have separate chapters on configuration and adding a provider, there should be no need to repeat those in the Vagrant, Docker and Cloud sections.
* Added some instructions for port mapping on Vagrant. I've chosen port 8443 as the standard port, and use that for Docker as well.
> Cleanup to the getting started guide.

- exe/miq
- lib/miq.rb
- lib/miq/lwimiq.rb
With this revision I mostly wanted a generator that took the pain out of
fiddling with dates and inserting them into GitHub URLs, and also
provide a skeleton that represents the form I typically use every time I
make a LWIMIQ blog post. With this added, an author can type in the
start date of the week concerned and get a blog post skeleton back with
working links.
The intention of this is not to set that form in stone - I love reading
posts that deviate from this formula, or even abandon it completely. But
I personally like having a blog post skeleton that gets me over the
blank canvas stage.
@hayesr LMK what you think, especially if my namespacing/documentation could use a little help :wink:
> Add a LWIMIQ post generator

- site/_posts/2016-11-07-last-week-in-manageiq-bugs-and-npm.html.md
A new entry for Last Week in ManageIQ.
Apparently the last one went only until the friday 28th, so this one is actually for the 9 days until (including) this Sunday.
> LWIMIQ - bugs & npm - Oct 29 to Nov 6

- Gemfile.lock
- site/_posts/2016-11-11-vote-on-naming-f-release.html.md
Post date was in the future (when checked without timezone?), preventing it from being built. 
Might be a Jekyll bug, or related to bad config somewhere.
This also bumps gem versions.
> Gem bump and fix blog post timestamp

- site/_includes/triad.html
- site/download/index.md
Fields:
- `eventCategory`
- 'Getting Started' refers to the quick start guides
- 'Appliance' refers to the appliances for downloading
- `eventAction`
- 'triadclick': clicked from the triad in front page (to differentiate clicks from other sources)
- 'outbound': link to external site for the download (e.g. for Docker and Vagrant)
- 'download': link to image on releases.manageiq.org
- `eventLabel`
- the type and release, e.g. oVirt Nightly, OpenStack Darga-5
> Google analytics event tracking for downloads and triad clicks

- site/_data/github_repos.yaml
- site/community.md
Link to contributors of the following repos under ManageIQ:
- manageiq
- manageiq-ui-classic
- manageiq-ui-service
- manageiq-appliance
- manageiq-appliance-build
- manageiq-content
- manageiq-gems-pending
- manageiq-providers-amazon
- manageiq-providers-azure
- manageiq-providers-lenovo
- manageiq-api-client
- manageiq-pods
- manageiq_docs
- integration_tests
- ui-components
- manageiq.org
More repos can be added to github_repos.yaml
Change sprint review frequency info as announced today (3 weeks -> 2 weeks)
> Add more contributor links to various repos

- site/_posts/2017-01-05-schedule-change-3-week-sprints-to-2-week-sprints.md
Notifying the change of sprint length from 3 weeks to 2 weeks.
> Sprint schedule change - blog post

- site/_posts/2017-01-06-sprint-51-review-january-4-2017.html.md
Reworded the provider section so it doesn't sound like the Provider Generator was related to XLAB work.
> Sprint 51 blog post - provider fix

- .gitignore
- .gitmodules
- Dockerfile
- exe/miq
- lib/miq/guides.rb
- lib/miq/ref_docs.rb
- test/lib/miq/guides_test.rb
This removes the `guides` submodule and handles them like the `manageiq_docs` repo.
The git submodule seems like a good idea, but it means a PR to bump the version for every change and submodules can be a pain to deal with. Also this is more consistent.
> Change how developer guides are built

- lib/miq/lwimiq.rb
This link has a problem which I believe can't be solved using the GitHub
API:
* if a commit was created before the time period, but merged during the
time period, it will not appear
* if a commit was created during the time period, but merged after the
time period, it will retroactively appear, changing the stats
The best alternative I have found to this is running something like the
following in the ManageIQ repo:
```bash
git rev-list --since=<start date> --before=<end date> --merges master | while read rev; do git rev-list $rev ^$rev^; done | wc -l
```
However, I don't think there's a sane way to include that in the generator.
/cc @Fryguy @chrisarcand
> Remove commits merged link from lwimiq generator

- lib/miq/lwimiq.rb
After the split it became apparent that there's a lot of work that goes
on outside of the "main" repo. So I've added links to what seem to make
up most of the work, and generalized the building of the link so it
should be easier to add/remove (and even read) in the future.
> Add links to PRs from main repos, post-split

- site/_assets/css/_menu.scss
Addresses #426
This code allows for scrolling menus if they get too long, but adjusts to account for the length of API doc menu items.
**before**
**after**
> Fix hidden menu items in API docs

- exe/miq
- lib/miq/lwimiq.rb
Instead of passing a command line argument to the generator for the
date, have the generator work out what the dates should be for last
week. If you're trying to produce one ahead of time, you can pass the
optional `--current` argument to generate the post for the current
week.
/cc @JPrause
> Have lwimiq generator work out the dates

- lib/miq/lwimiq.rb
Also omits the time, which seems to be problematic.
@miq-bot assign @hayesr
> Make lwimiq publication date current/next tuesday

- site/_data/download_types.yaml
- site/download/index.md
Fixes https://github.com/ManageIQ/manageiq.org/issues/464
(Didn't add the 'direct link' mentioned in https://github.com/ManageIQ/manageiq.org/issues/464 as Vagrant doesn't have it either...)
Marking as WIP as `-devel` links for EC2/GCE nightly builds (e.g. http://releases.manageiq.org/manageiq-ec2-devel.vhd) don't exist yet. Not sure how/where that's done.
/cc @Fryguy
> Add AWS EC2 and GCE images to download page

- site/download/index.md
Both stable and pre-release images are uploaded to google cloud, so direct user there instead of releases.manageiq.org.
@hayesr please review
> Change GCE pre-release download link to google cloud storage

- site/_includes/head.html
"a full URL is needed for Open Graph (the spec does not say this explicitly, but all examples there are full URLs, and some parsers expect them)" https://meta.stackexchange.com/questions/264186/meta-should-use-a-full-url-for-its-open-graph-image
> Use full URL for Open Graph meta tag

- site/_posts/2017-06-05-extractions.md
Didn't notice <important news> tag was still in the post
> Removed generator tag

- site/community.md
Both Vienna.rb meetup as well as AnsibleFest are now in the past.
> moved upcoming events to past events

- site/download/index.md
Export compliance terms are missing from the ManageIQ site. Adding them to download page.
> Add Export Regulations to Download page

- exe/miq
Improves the documentation for the generator.
Before:
```
tim@tim-thinkpad:~/src/manageiq.org$ bin/miq generate help lwimiq
Usage:
miq lwimiq
Options:
[--current=CURRENT]  
Generate a LWIMIQ blog post
```
After:
```
tim@tim-thinkpad:~/src/manageiq.org$ bin/miq generate help lwimiq
Usage:
miq generate lwimiq
Options:
[--current], [--no-current]  
Description:
Generates a new Last Week in ManageIQ blog post skeleton. Includes all the links for PRs merged in the last week in the various ManageIQ repositories.
With --current option, bin/miq generate lwimiq generates links based on the current week instead of the last.
```
> Improve lwimiq documentation

- site/_assets/css/_triad.scss
This PR tweaks to styling of the "Try it!" images to render properly on tablet and mobile
Before
After
> Adjust images for proper rendering on tablet/mobile

- site/docs/get-started/add-a-provider.md
Changed the provider link to the documentation page "Managing Providers" (https://manageiq.org/docs/reference/latest/doc-Managing_Providers/miq/)
> Changed the provider link

- site/_posts/2017-09-21-finalizers-can-be-interrupted-from-time-to-time.md
Dev blog: Timeout can raise exceptions in object finalizers, leading to very
strange bugs.
> Finalizers can be interrupted from time to time

- site/_posts/2017-09-21-finalizers-can-be-interrupted-from-time-to-time.md
Fix the format of the really long command output by removing some extra cruft and using a horizontal scrollbar using fancy `<code` tags.  ✨ 
Fix the publish time and date for @Fryguy without renaming the file to match.  :trollface: 
@Fryguy @imtayadeway @cybette please review
> Fix finalizers formatting finally

- site/_data/github_repos.yaml
I add the repo of Hawkular to the community site.
> Add Hawkular Provider to the community view

- site/_data/download_types.yaml
- site/download/index.md
QCOW2 appliance image is used for for RHV 4.0 and newer. Currently we only have the OVA appliance (which is for RHEV 3.6 and earlier). This PR adds the qc2 option to the download page, as well as update some of the image size information.
Addresses issue: https://github.com/ManageIQ/manageiq.org/issues/613
> Add ovirt qc2 option to download page

- Dockerfile
Based on https://github.com/ManageIQ/container-ruby/pull/4
> The ruby container now installs ruby with --system so paths have changed

- site/_posts/2018-02-14-the-pathname-to-discovering-a-memory-leak-in-ruby.html.md
Goals:
------
Being that this is a slightly different post from the typical LWIMIQ and MIQ release posts, I figured I would share the general goals for this post.
In no particular order:
* Describe to the broader ruby community a bug that could cause issues for other ruby/rails developers (in fact, [it has](https://github.com/opf/openproject/pull/6148))
- Hopefully explain this in a way that doesn't require too much MIQ domain knowledge allowing for engagement outside of the MIQ community
* Share and explain the process used to diagnose and fix this issue, so that possibly others might learn something from it
* Explain to the ManageIQ/CFME the issues they might have been seeing in their environments
* Avoid putting people to sleep...
- I have been known to be long winded individual when …
> Ruby Memory leak in MIQ blog post

- site/_posts/2018-02-14-the-pathname-to-discovering-a-memory-leak-in-ruby.html.md
Fixes a few things that "leaked" through...
1. `require config/environment.rb` -> `require 'config/environment.rb'` (added quotes
2. Fixes Finn & Jake high-five (markdown thought it was a table...):
- Before
- After
3. Makes the reference to step 4 clearer:
- Before: "(`4.` from the list above)"
- After: "(step \# 4 from the list above)"
4.  Same for a reference to "Step \# 1.5"
5. Fix tag:  `development` -> `developers`
> Mem leak post cleanups

- site/_posts/2017-09-29-miqldap-to-sssd.md
Arguments bind-dn and bind-pwd were added to miqldap_to_sssd
in PR: https://github.com/ManageIQ/manageiq/pull/16979
This PR updates the miqldap-to-sssd blog post to include
descriptions of these two new arguments.
> Describe new miqldap-to-sssd arguments.

- site/_posts/2018-01-31-troubleshooting-auth.md
While working with customer support I realized the `domainname` attribute was not shown
in the dbus-send example.
This PR simply adds the `domainname` to the appropriate dbus-send example.
> Add domainname attribute to dbus-send example

- site/_data/menus/api_menu.yml
Changes in API doc structure in new version needs to be reflected on the MIQ website.
http://talk.manageiq.org/t/api-refrerence-404-on-some-urls/3449
> Update reference items in API menu for v3.0.0

- site/_assets/css/_syntax-highlighting.scss
- site/_assets/css/main.scss
- site/_posts/2017-09-21-finalizers-can-be-interrupted-from-time-to-time.md
- site/_posts/2017-09-29-miqldap-to-sssd.md
- site/_posts/2018-01-31-troubleshooting-auth.md
Issue
-----
There were two main issues that are being addressed:
* Code blocks were doing "word wrap" by default
- This was brought in a CSS rule from `"bootstrap/code"`
- It has been worked around previously using `<pre><code style="white-space: pre">` directly (looks ugly...)
* Syntax highlighting was being handled in the markup, but wasn't highlighted by the CSS
- Seems to have been introduced a while ago when patternfly was removed from this repo
The Fix
-------
To resolve the above:
* Included the `_syntax-highlighter.scss` into the `main.scss` file
* A updated rule was added to override the `"bootstrap/code"` addition we don't want (second commit)
In addition:
* Added a `console` specific color theme to add emphasis to terminal based code snippets (third commit)
- This commit is …
> Fix code block formatting/syntax highlighting

- site/docs/get-started/concepts.md
Postgresql 9.4 is no longer supported, and the rest also changed since the last update.
> concepts - update CentOS, PostgreSQL and Rails versions

- site/download/index.md
vagrant box name didn't get updated when we started `hammer` pre-release, so updating now..
@cybette @JPrause  Currently, index.md has docker and vagrant release specific data in the file (docker image size, vagrant image size and box name).
I think the index page should be refactored so everything about releases (branch name, box name, etc.) live in `site/_data/releases.yaml` and everything about image details live in `site/_data/download_types.yaml`
Otherwise it will be easy to miss an update, like this time...
> Update vagrant box to hammer for pre-release

- site/community.md
**Before:**
**After:**
Fixes #690
> Fix the iframe rendering for the build stats on the Community page

- site/_posts/2019-01-09-manageiq-provider-operations-with-ansible-xlab.md
@JPrause @Fryguy please take a look
> Blog post featuring XLAB on provider operations with Ansible

- site/_assets/css/_blog.scss
- site/_assets/css/_off_canvas.scss
- site/_assets/css/main.scss
- site/_layouts/blog_month.html
- site/_layouts/blog_year.html
- site/_layouts/post.html
- site/_layouts/tag_index.html
- site/blog/index.html
This PR redesigns the blog section of the website to use the bootstrap 3 grid system.  Right-menu items are now accessible at the bottom of the mobile layout rather than being invisible.
Issue : #378
Old (fixed layout)
New (fluid layout)
Old (completely missing menu in mobile mode)
New
> Responsive redesign of blog section

- site/_data/menus/ref_menu_hammer.yml
- site/_data/menus/ref_menu_latest.yml
New reference page introduced in Hammer, it has already been built and is [available online](http://manageiq.org/docs/reference/hammer/auth/openid_connect), but the menu item is missing. 
@jvlcek please check
@epwinchell please merge if everything looks ok.
Thanks!
> Add OpenID-connect to User reference menu so it pulls in the content

- lib/miq/ref_page.rb
Not uglier than the rest of the code around it :tornado:
> Do not generate branch_path for documentation items that don't exist

- lib/miq/ref_docs.rb
When calling the `mv` to an existing destination, it doesn't merge the files. Therefore, we first have to drop the old folder so we can pull in the new changes.
It might caused bugs in the website, not sure about it. But this is definitely *The Right Way&trade;*
> Drop the latest folder when retrieving docs to allow to overwrite

- site/_data/menus/guides_menu.yml
This PR adds "Debugging" to the Developer Setup menu in guides
> Dev menu update

- .travis.yml
Ruby 2.3 is getting EOL in a few days and we're using 2.4 in the container that runs the website anyway...
> Update ruby version to 2.4 to match the container we're using

- site/community.md
- site/events.md
This PR moves the existing Events section from The Community page to a new Events page.
Related issue: https://github.com/ManageIQ/manageiq.org/issues/705
> Create new Events page

- site/community.md
- site/events.md
This PR moves all events under "Past Events"  and removes an old "Upcoming Events" title from  the community page
> Calendar update

- site/_data/download_types.yaml
Dropping OVA for oVirt/RHV as the currently supported versions of oVirt/RHV (4.x) all support qcow2. Note, our documentation for RHV talks about using qc2 image and not ova.
Related PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/354
> Drop OVA for oVirt/RHV

- site/_data/download_types.yaml
- site/download/index.md
Added Vagrant in download 'nightly' section, linking to releases.manageiq.org since we don't publish nightly images to vagrantup (just like GCE).
Also refactored the docker/vagrant list so it uses the same format as others , and dry'ed up column title.
> Add Vagrant download for nightly and refactoring

- site/community.md
Let's Meet is not needed, here.  Community Events section above takes care of this.
Added link to the document on google drive that has links to both slide decks and review recordings.
(p.s. I tried to be able to run the web site locally to see what it would look like, but no luck, there)
> Add link to Artifact Doc and Remove Let's Meet

- site/community.md
This PR updates and reorganizes the Community page with the following changes:
- remove the ManageIQ Depot link
- rename "Develop" to "Collaborate"
- remove the list of individual repos, in favor of the "All repos under ManageIQ" link  in the Collaborate section.
- delete the  Open Hub graphic
- rebalance the layout
Issue: https://github.com/ManageIQ/manageiq.org/issues/786
Issue: https://github.com/ManageIQ/manageiq.org/issues/788
Issue: https://github.com/ManageIQ/manageiq.org/issues/789
Old 
New
> Reorganize Community page

- site/_config.yml
This PR renames the  'gems' configuration option to 'plugins'.
> Rename 'gems' to 'plugins'

- lib/miq/md_link_converter.rb
- test/lib/miq/md_link_converter_test.rb
Fixes https://github.com/ManageIQ/manageiq_docs/issues/555
> Fix md_link_converter to not strip off .md suffix for external links

- site/_data/menus/api_menu.yml
- Update the API menu to reflect the new compliance policy usage flow example page.
Relates to: https://github.com/ManageIQ/manageiq_docs/pull/1390
/cc @gtanzillo I think this is what was missing.
> Update the API menu to reflect the new compliance policy usage example page

- site/_sprints/137.md
- site/sprints/index.html
Adding the stub exposed a bug that is addressed by this [commit](https://github.com/ManageIQ/manageiq.org/pull/841/commits/4982c05fb5cfe80c4f6d045f79c16143053dc67c) to fix sprint index to display details ONLY if GitHub data (on which the details page is based) is available
> Add stub for Sprint 137 so we can see Merged PRs while sprint is ongoing

- site/docs/get-started/docker.md
Use systemctl for docker service instead of init scripts (systemd
has been the default init system in Fedora since 2011 and Ubuntu since
2015)
Additionally the docker command line shouldn't need to be run with
sudo
> Fix issues with docker quickstart

- lib/miq.rb
- lib/miq/ref_docs.rb
@chessbyte Please review.  [ManageIQ/manageiq_docs@jansa](https://github.com/ManageIQ/manageiq_docs/tree/jansa) has already been synced with its master and adjusted to act as the primary build target [[1]](https://github.com/ManageIQ/manageiq_docs/commit/c3ea176668317a2db8db824eb320fa8f48c7fc83).
> Update docs build to build from jansa branch as the latest

- lib/miq/ref_page.rb
- lib/miq/ref_versions.rb
- site/_includes/head.html
- site/_plugins/canonical_url.rb
- test/lib/miq/ref_versions_test.rb
> Add support for canonical URLs

- exe/miq
- lib/miq/site.rb
Allows for the following:
`exe/miq build site --trace`
`exe/miq build all --trace`
This option adds --trace to the `jekyll build` command that is executed under the covers.
> Add --trace option to build CLI

- site/_posts/2019-12-06-introducing-new-provider-microsoft-azure-stack.md
As we have shifted the main page to focus more on Ansible, I wanted to update this 
blog post to our original page, showing our CloudForms integrations.
> Change the Steampunk link

- site/_posts/2019-12-06-introducing-new-provider-microsoft-azure-stack.md
In the last update I missed the fact that there were two links. I am fixing the second one now
as the link in the page does not make too much sense.
> Fix the remaining link to Steampunk

- site/_posts/2020-09-03-oidc-auth-api-usage.md
When testing these instructions with IBM's Identity Access Management (IAM) provider I uncovered three issues.
These updates will ensure this blog post will correctly apply to both  IBM's Identity Access Management (IAM) provider and Keycloak.
The three issues addressed with this PR are:
1. Add parameter scope=openid which is required on IAM and OK with Keycloak
2. Remove unnecessary user flag when getting the jwt
3. Add jq to improve introspection output
> Fix oidc api

- site/_data/menus/guides_menu.yml
There's a dead link to the 'Minimal Mode' guide. Looks like this was missed when removing MIQ_SPARTAN: ManageIQ/manageiq/pull/20401
> Remove dead link to 'Minimal Mode' guide

- site/_posts/2020-09-03-oidc-auth-api-usage.md
The value of oidc_provider_token_endpoint varies based on the configuration and the OpenID-Connect Provider being used.
This PR will describe the different values for oidc_provider_token_endpoint when using Keycloak and IAM.
> Specify the different possible values for oidc_provider_token_endpoint 

- site/_includes/triad.html
Follow up to #910 , but so we never have to remember to do it again 😄 
Note that this will now say `Jansa-1` instead of `Jansa`, but I think that's fine (or maybe it's gaprindashvili).
> Make the release name dynamic

- site/_includes/download/release_table.md
Since Jansa is the stable release now, adding kubernetes/openshift to the download page (Jansa was prerelease when they were added in https://github.com/ManageIQ/manageiq.org/pull/842).
> Add Kubernetes and OpenShift to stable release download page

- site/_data/sprints/gh_152.yaml
Since Sprint 152 was extended to a 4-week sprint (due to the winter holidays), the GitHub statistics needed to be updated as well.
> Update Sprint 152 Statistics

- site/_plugins/download_filter.rb
On some browers, download doesn't work due to insecure connection, so switching to HTTPS.
> Use HTTPS for appliance download

- site/_config.yml
While canonical URLs were put in the headers of these old docs, they are
ignored by google because of their presence in the sitemap.  According
to Google, all URLs in the sitemap are automatically considered
canonical, and thus are crawable/searchable.
@chessbyte Please review
> Remove non-canonical URLs from the sitemap

- README.md
* Update `manageiq-documentation` section (we use Markdown now)
* Clean up table formatting for plaintext viewing
> README.md updates 2021-09

- site/download/index.md
Digital Ocean does not auto link a directory to the html page.
Currently, releases points to an xml document, which is a bit overwhelming.
The html page is easier to view and understand.
> point releases to html page

- site/_assets/css/_twbs_overrides.scss
- site/_assets/css/themes/_dark.scss
- site/_assets/css/themes/_light.scss
Fixes buttons in pagination in dark mode.
Fixes #1012
> [_twbs_overrides.scss] Fix pagination

- site/_assets/css/_labels.scss
- site/_assets/css/main.scss
Adds styles to that label page that can allow removing the need for `</br>` tags in the markdown (which don't even render properly in some processors).
Links
-----
- Merge with https://github.com/ManageIQ/guides/pull/471
> Add _labels.scss

- site/_assets/css/_colors.scss
- site/_assets/css/_page.scss
- site/_assets/css/_site_nav.scss
- site/_assets/css/themes/_dark.scss
- site/_assets/css/themes/_light.scss
- site/_assets/css/themes/_toggle.scss
- site/_includes/head.html
- site/_includes/site_nav.html
- site/assets/js/_theme.coffee
- site/assets/js/main.coffee
Allows switching between dark/light themes, regardless of OS preference.
In this case, the theme will first be determined by the OS/Browser theme preference.  Then, when the toggle button is switched, it will override that value with a css class ('.light-theme' or '.dark-theme') on the top level `<html>` tag.  This with then switch the theme to the one preferred by the user, and save that preference in local storage.
When the page is reloaded or a new page is accessed, it will check that value first before trying to render the page.  This is why some raw JS code is required in `_head.html` since it is used to render the theme prior to the full page load.
Font awesome icons for "sun" and "moon" are used for the toggle switch, but they don't use the built in CSS classes since it is one less …
> Add theme switcher

- Gemfile
It seems that a more recent version of bundler caused the version of Rails to downgrade from 5.2.7 to 5.2.6.3, which is when the failures started.
> Fix build failures after downgrade from Rails 5.2.7

- site/docs/get-started/kubernetes.md
This page was built when kubernetes was still in beta, but now that it's
been shipped we should be pointing to the stable release. This fixes the
`git checkout` line as well as the link to the `README.md`
documentation.
Replaces #1089 
cc @hobbert
> Fix issue when prerelease doesn't exist

- site/docs/get-started/add-a-provider.md
Link to "support options document" (2nd link on page) is broken.
> Fix broken link

- .github/workflows/ci.yaml
There is an issue in CI with building libv8 that has been fixed in a
newer rubygems.  Instead of just upgrading Ruby gems, we might as well
update Ruby itself.
> Upgrade Ruby to 2.7

- site/_posts/2013-11-20-inspectxml-dump-objects-as-xml.md
- site/_posts/2017-11-24-implementing-continuous-integration-for-cloudforms-using-git-and-travis.md
- site/_posts/2018-01-12-my-first-contribution-to-manageiq.md
- site/_posts/2018-02-13-automating-instance-provisioning-with-cloudforms-and-ansible-tower-video.md
- site/_posts/2018-02-23-cloudforms-database-high-availability-explained.md
- site/_posts/2018-03-22-cloudforms-on-aws-part-1-series.md
- site/_posts/2018-03-27-cloudforms-in-aws-part2.md
- site/_posts/2018-04-02-cloudforms-in-aws-part4.md
- site/_posts/2018-04-09-cloudforms-in-aws-part5-authenitcation.md
- site/_posts/2020-06-26-cloudforms-blog-is-moving-to-manageiq.md
These blog tags clutter up the list of tags and generally only point to
one article, but aren't really useful for various reasons.
@jrafanie Please review.
> Cleanup some blog tags that aren't useful

- Gemfile
bundler 2.4's new resolver is resolving jekyll-assets to a newer version
(3.0.12; was 2.4.0), which, in turn, is bringing in a major version bump
of sprockets (4.0.3, was 3.7.2). This version of sprockets has a
different interface in the find_directory_manifest method which is
overridden by jekyll-assets. See https://github.com/envygeeks/jekyll-assets/pull/636
This can be seeing in the error during the build:
```
bundler: failed to load command: jekyll (/home/runner/work/manageiq.org/manageiq.org/vendor/bundle/ruby/2.7.0/bin/jekyll)
/home/runner/work/manageiq.org/manageiq.org/vendor/bundle/ruby/2.7.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/manifest.rb:58:in `find_directory_manifest': wrong number of arguments (given 2, expected 1) (ArgumentError)
from …
```
> Fix issue where a newer jekyll-assets is breaking the build

- lib/miq/ref_docs.rb
This is mostly for development where you make changes in a branch in manageiq-documentation, but then it builds master (and not your branch) anyway. This ENV var allows you to pretend you development branch is "master".
Example usage:
```
MIQ_REF_REPO=~/dev/manageiq-documentation MIQ_REF_MASTER=bullet_list_journalctl MIQ_ENV=production BUNDLE_WITHOUT=test:development bundle exec exe/miq build all
```
@agrare Please review.
> Allow passing MIQ_REF_MASTER to build a different branch for docs

- site/assets/js/_theme.coffee
- site/assets/js/main.coffee
Before this commit, the code that attaches the event listener only looked at the first instance in the header, but misses the footer. After this commit it looks at all instances.
> Fix issue where theme switcher in the footer didn't work

- site/_plugins/download_filter.rb
> Add some logic for following redirects

- site/_assets/css/_type.scss
- site/_data/download_types.yaml
- site/_includes/download/release_table.md
@jrafanie Please review.
Preview:
> Add note about which download types are non-production/PoC

- site/_posts/2017-09-29-miqldap-to-sssd.md
- site/_posts/2018-01-31-troubleshooting-auth.md
- site/_posts/2018-02-01-auth-overview.md
@jrafanie Please review.  I forgot that this doesn't expect `, `, so the tag on the website right now is literally `ldap,` 😑
> Fix tags doesn't support commas

- site/_posts/2024-05-29-manageiq-quinteros-ga-announcement.md
- site/changelog/index.md
- site/changelog/petrosian-1-to-quinteros-1.md
- site/community.md
This adds a new full-changelog set of pages, initially populated with petrosian-1 to quinteros-1.  This page is more or less generated by using the show_commit_history command from multi_repo, so it is easy to generate at release time.  I'll have a future PR with README or Wiki instructions on how to generate the page, but for now I wanted to get it committed and get feedback on the look and feel.
Eventually, I also want to remove the changelogs from the specific repos, and just use this webpage instead.
> Add release changelogs initially with petrosian-1 to quinteros-1

- site/_data/releases.yaml
- site/_posts/2024-11-14-quinteros-2-cve-2024-43191-cve-2023-46715.md
- site/changelog/index.md
- site/changelog/quinteros-1-to-quinteros-2.md
@bdunne Please review.  Once you are ready to go, this has the details.
> Release quinteros-2

- lib/tasks/sprint_defails.rake
@jrafanie Please review. This is admittedly rough, but I think committing something is better than nothing.  I need to do a reorganization of the code in the sprint_statistics repo before I can truly make this "good"
> Add rake task to aid in creating sprint details

- Gemfile
This dependency version was not set. versions <= 1.4.0 are vulnerable.
Since this is not shipped, the exposure is minimal, but best to keep up to date
See CVE-2025-54314 https://github.com/advisories/GHSA-mqcp-p2hv-vw6x
> Declare thor version CVE-2025-54314
